name: CI

on:
    push:

jobs:
    build-and-test:
        name: build & test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js, PNPM, and install dependencies
              uses: ./.github/actions/pnpm-install

            - name: Build all
              working-directory: ./typescript
              run: pnpm build

            - name: Test all
              working-directory: ./typescript
              run: pnpm test